server:
  port: 8080


spring:
  application:
    name: student
  datasource:
    url: jdbc:postgresql://localhost:5433/student
    username: amigoscode
    password: password
  thymeleaf:
    check-template-location : true

    cache: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:8180/auth/realms/microservices-realm

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:5672
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
